# Generated by Django 5.1.3 on 2024-11-22 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_user_user_email_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, default='avatars\\Login_default_Avatar.png', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
