# Generated by Django 5.1.3 on 2024-11-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_project_team_alter_user_user_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Message',
            new_name='message',
        ),
    ]
